### ISSUE TITLE
Minimum Viable Product - Solve a problem I have

### ISSUE THREAD

**Issue by simonireilly** [simonireilly/microteams#6]
As a user of AWS I find I am continually starting new projects.

### Experienced AWS User

The experienced user knows AWS security best practices and IaC for AWS. They have knowledge of Cloudformation, Terraform, and potentially others. This expert wants to achieve best practices.

### Intermediate AWS User

The intermediate user is woke to the idea that they can be improving how they manage AWS. They have had issues worked through in IAM, and know how to fix the rough edges of deploying to AWS.

### Novice AWS User

The novice user is new to AWS and has possibly been captured by a marketing funnel like the serverless framework. They just want things to work, and don't understand best practices.

## Requirements

Each new project would have a scenario such as:

- Create an AWS account in the AWS Organisation with an SSO user for that organization
- Write some code that I know I want to deploy via a CI/CD pipeline
- Write the CI/CD pipeline and create a role, store the access key and secret access key for that role

What would I rather do:

```bash
microteams new <project_name>
```

## Outcomes

- [ ] #7
- [ ] #9
- [ ] Come up with a solution for starting from micro-teams
- [ ] Come up with separate journeys for users that want to have a single account
- [ ] Come up with separate journeys for users that want to have multiple accounts as dev/prod etc.
- [ ] Come up with separate journeys for users that want to have many accounts, in organizational units structuring
